### ISSUE TITLE
Valhalla Hobby Separation Issues

### ISSUE THREAD

**Issue by Siouxxanne** [Comics-Games-and-Things-LLC/openCGaT#3]
500 error when attempting to create new product.

Exception Type: ValueError at /shop/manage/valhalla-hobby-cgt-verona/product/vallejo-28531-acrylic-matt-varnish-spray-400ml-copy-1/edit/
Exception Value: The file 'wagtailadmin/css/normalize.css' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f467f3b9810>.
Raised during: shop.views.add_edit_product

**Comment by Siouxxanne** [comment]
Recurring cart error in django errors folder. Not sure if important:

Exception Type: ValueError at /cart/cart/
Exception Value: 'Cart' instance needs to have a primary key value before this relationship can be used.
Raised during: checkout.views.json_cart

**Comment by Siouxxanne** [comment]
Unable to intake:

Exception Type: IntegrityError at /partner/valhalla-hobby-cgt-verona/intake/intake/8437013061483
Exception Value: duplicate key value violates unique constraint "shop_inventorylog_pkey"
DETAIL:  Key (id)=(2) already exists.

**Comment by nstephenh** [comment]
Fixed with updating wagtail rich text field and fixing all our key sequence issues with:
`
python manage.py sqlsequencereset shop checkout discount_codes | python manage.py dbshell
python manage.py sqlsequencereset partner payments posts realaddress shop user_list userinfo | python manage.py dbshell
python manage.py sqlsequencereset game_info giveaway images intake inventory_report | python manage.py dbshell
python manage.py sqlsequencereset billing checkout credit digitalitems discount_codes  events financial | python manage.py dbshell


`
